### ISSUE TITLE
关于数据处理

### ISSUE THREAD

**Issue by JayceWen** [AXYZdong/AMchat#9]
大佬好，你的工作很惊艳，我对此很感兴趣。能否请教一下细节问题？
1.您大概用了多少数据进行lora微调呢？
2.想了解一下下图部分具体是怎么做的呢？
<img width="458" alt="image" src="https://github.com/AXYZdong/AMchat/assets/53989593/b37283e5-6e8d-4630-8bc7-0886b96bb2ae">

**Comment by AXYZdong** [comment]
目前项目还在持续更新中，相关技术细节会逐渐更新，敬请期待~
